CREATE DATABASE PATIENTS_DB;

USE PATIENTS_DB;

CREATE TABLE patients ( MOBILE varchar(200) NOT NULL, NAME varchar(200) NOT NULL, DOB varchar(200) NOT NULL, HISTORY varchar(200) NOT NULL, MEDICINES varchar(200) NOT NULL, PRIMARY KEY (MOBILE) );
show tables
select * from PATIENTS_DB;


